### ISSUE TITLE
Handling secret keys and credentials

### ISSUE THREAD

**Issue by jrhorn424** [rememberlenny/national-fever-tracker#11]
See #12

These keys allow me to add API keys to the configuration files use `rails credentials:edit`.

Do not commit these files to VCS. Back-channel them to me, please.

**Comment by jrhorn424** [comment]
I can blow all these away, maybe. I tried regenerating with `master.key` and `credentials.yml.enc` removed, but didn't have much success.

**Comment by jrhorn424** [comment]
Yes, I can regenerate all the keys and share with developers as needed. That makes me a bottleneck. I'll work with @joybuchanan to figure out how we want pass these around as needed.

**Comment by joybuchanan** [comment]
I would give you and Aaron both direct access to update the master.
I would prefer to have someone review any changes I make to code, if
someone can do it quickly. On the other hand, I do believe that I can be
very conservative in my changes and not break anything.

I don't know David as well. I believe he'd be happy to have people
review his code, to take pressure off.

Not sure if that's what you were asking, but seemed relevant.

**Comment by jrhorn424** [comment]
Development will go in fits in starts. Without sharing key files, we’ll each have to recreate credentials each time we develop. It is also good if more than one of us can deploy, but we can’t do that without those keys. They are a feature of Rails and have to be shared secretly (never exposed on the web; email is fine). @rememberlenny will have the originals he used and can share them with us however he likes.

**Comment by rememberlenny** [comment]
Hey!

The best way to access the keys is directly on Heroku.

—
Leonard Bogdonoff
RememberLenny.com | 949-322-8496

**Comment by joybuchanan** [comment]
I just invited Jeff to the Heroku (I think)
Joy

**Comment by jrhorn424** [comment]
The builds will continue to fail until we add the appropriate keys to the build pipeline. Heroku only includes the master key, not the development, test, or staging keys which may also be needed.

Would you like me to zip mine up and share them, or will you share yours @rememberlenny?

**Comment by jrhorn424** [comment]
PR incoming.
