### ISSUE TITLE
Typo in "6am" button

### ISSUE THREAD

**Issue by joybuchanan** [rememberlenny/national-fever-tracker#4]
When users go to make their first email account at 
https://nationalfevertracker.com/tracker_reminders/new
"6pm" should be "6am"

**Comment by free-soellingeraj** [comment]
Those labels are found here:
https://github.com/rememberlenny/national-fever-tracker/blob/master/app/views/tracker_reminders/_form.html.erb

**Comment by joybuchanan** [comment]
I edited the code and committed the change, but nothing is reflected in the website, yet

**Comment by joybuchanan** [comment]
Run failed for master (292987c)
Repository: rememberlenny/national-fever-tracker
Workflow: Tests
Duration: 5 minutes and 2.0 seconds
Finished: 2020-04-02 13:48:24 UTC

is the message I got by email

**Comment by rememberlenny** [comment]
That test failure can be ignored. I dont think it was working before either. The change is good!

**Comment by joybuchanan** [comment]
The change is good! : )

**Comment by free-soellingeraj** [comment]
Hey Lenny

Glad to hear from you.  Ya we're getting up to speed on the rails app.

It would be useful if you could write down the steps you take to push
updates to the heroku.  We could go over them together and then there would
be 2 of us that could push code to the production system.

Let me know what you think.
--aaron
